### ISSUE TITLE
What are the Slicer Settings for this printer?

### ISSUE THREAD

**Issue by NWalen** [eclsnowman/Eustathios-Spider-V2.5#1]
I have the Start and End Gcode set but now i just need the speed Settings such as acceleration and what speed to print at.

**Comment by eclsnowman** [comment]
Are you still running the old Marlin configuration 2.0.7, newer Marlin like 2.1.2.1 with I.S. enabled, or have you switched to Klipper? Input Shaping can vary the commanded print speeds and accelerations I use pretty dramatically. Secondly, what slicer and print material are you currently trying to tune in? Print settings can vary fairly extensively depending on print shape, layer size (hence max flow rates), and each slicer has some unique features which may change the speeds I utilize.

**Comment by NWalen** [comment]
I am running Marlin 2.0.7 but im working on Marlin 2.1.2.1 For filament runout. I use OrcaSlicer With PLA+

**Comment by NWalen** [comment]
And im using the Default Marlin Setup in OrcaSlicer
